name: Deploy to github pages

on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm i -g yarn
            -   run: yarn install --frozen-lockfile
            -   run: |
                    yarn build
                    yarn export
            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@4.1.4
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    branch: gh-pages # The branch the action should deploy to.
                    folder: out # The folder the action should deploy.